name: ecommerce_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cupertino_icons:
  get: ^4.6.6 # for state management and context less stuff
  flutter_screenutil: ^5.9.0 # make app responsive
  shared_preferences: ^2.2.2 # shared preferences persistence key value store
  flutter_launcher_icons: # change app icon
  change_app_package_name: # change package name
  rename_app: # rename app
  flutter_svg: ^2.0.9 # for svg icons
  flutter_animate: ^4.5.0 # for animation
  smooth_page_indicator: ^1.1.0 # for onboarding page indicator
  google_fonts: ^6.1.0 # for custom fonts
  logging: ^1.2.0 # for logging
  razorpay_flutter: ^1.3.7 # for payment gateway integration

  flutter:
    sdk: flutter

dev_dependencies:
  mockito:
  flutter_lints:
  build_runner:
  get_cli:

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/shoes/
    - assets/accessories/
    - assets/bags/
    - assets/babies_clothing/
    - assets/vectors/
    - assets/fonts/
    - assets/images/card1.png
    - assets/images/card2.png
    - assets/images/card3.png
    - assets/images/clothing.jpg
    - assets/images/accessories.jpg
    - assets/images/bags.jpg
    - assets/images/footwear.jpg
    - assets/images/signUp_dark.png
    - assets/images/Illustration-0.png
    - assets/images/Illustration-1.png
    - assets/images/Illustration-2.png
    - assets/images/Illustration-3.png
    - assets/images/Illustration-4.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700